apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: tn-ai-validation-playground

namePrefix: beslisboom-

commonLabels:
  minbzk.github.io/name: beslisboom

buildMetadata: [originAnnotations]
